Component Chart
js-tasks-ru/js-20200821-3_fenix4088 pull request #2
Opened 2020-09-06 12:20 UTC by Fenix4088

2020-09-06 12:27 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
ColumnChart компонент
+ should be rendered correctly
+ should have ability to define label
+ should have ability to define link
+ should have ability to define total value
+ should have property 'chartHeight
+ should render data correctly
+ should have ability to be updated by new "data" values (should re-render only body with charts columns)
+ should have loading indication if data wasn't passed 
+ should have ability to be removed
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-09-07 11:23 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +        value = Math.floor(value);
зачем разбивать определение `value` на две операции, еще и через изменение `let`
Делайте проще:
```
const value = Math.floor((dataItem * this.chartHeight) / maxNumber);
```

2020-09-07 11:25 UTC, dosandk requested changes
Решение принимаю, но нужно убрать изменения из PR которые не касаются решения.
Также нужно убрать весь закомментированный код

2020-09-09 07:14 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-09-10 10:48 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.html
> +      <div id="orders" class="dashboard__chart_orders">
ну вот нельзя изменять системные файлы. Вот вообще нельзя и все! 
Почему эти изменения попали в PR?

2020-09-10 10:49 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +    this.data = obj.data || [];
все таки более предпочтительнее использовать дефолтные параметры аргументов, хотя конечно можно и с оператором "||"

2020-09-10 10:50 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +        let value = Math.floor((dataItem * this.chartHeight) / maxNumber);
это должны быть значения объявленные через `const`

2020-09-10 10:51 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +  static notificationStatus;
неудачное имя свойства, Вы там храните ссылку на DOM элемент, поэтому не вводите в заблуждения читателей Вашего кода, так как DOM элемент это не статус. Подумайте и переименуйте это свойство

2020-09-10 10:51 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2020-09-11 08:29 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- 05-dom-document-loading/2-sortable-table-v1/index.spec.js — изменен
```

2020-09-11 08:35 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- 05-dom-document-loading/2-sortable-table-v1/index.spec.js — изменен
```

2020-09-11 08:59 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- 05-dom-document-loading/2-sortable-table-v1/index.spec.js — изменен
```

2020-09-14 14:21 UTC, closed without merging